# Generated by Django 4.2 on 2023-04-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total',
        ),
    ]
